apiVersion: apps/v1
kind: Deployment
metadata:
  name: saloon-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saloon-service
  template:
    metadata:
      labels:
        app: saloon-service
    spec:
      containers:
        - name: saloon-service
          image: janindu3/saloon-service:latest  # Updated image path
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: saloon-service
spec:
  type: LoadBalancer
  selector:
    app: saloon-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
