apiVersion: v1
kind: Service
metadata:
  name: saloon-service
  namespace: saloon-system
  labels:
    app: saloon-service
spec:
  type: ClusterIP
  selector:
    app: saloon-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
